### ISSUE TITLE
Suche nach PLZ + Umkreis fehlerhaft?

### ISSUE THREAD

**Issue by physad** [bjoluc/freie-plaetze#1]
Suche nach PLZ + Umkreis fehlerhaft?

Bsp:

24119 als PLZ im Suchfeld + 50 km Umkreis => kein Ergebnis | Erwartet: 1 Ergebnis = fehlerhaft
24103  als PLZ im Suchfeld + 50 km Umkreis => 1 Ergebnis | Erwartet: 1 Ergebnis = korrekt

**Comment by bjoluc** [comment]
Danke @physad! Interessanter Weise funktioniert die Suche für die Eingabe "Kronshagen". Scheint ein Problem mit dem Geocoding-Backend zu sein. Für die Suchfunktion hosten wir eine Nominatim-Version im [admin-Import-Style](https://nominatim.org/release-docs/latest/admin/Import/#filtering-imported-data), was nicht für alle Postleitzahlen auszureichen scheint. Ich versuche mal den street-Style, in der Hoffnung, dass er alle Postleitzahlen abdeckt.
